AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Shared Python layer

Resources:
  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: common-utils-py312
      ContentUri: common-utils-py312/   # <- carpeta que contiene 'python/' y 'requirements.txt'
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.12            # <- CLAVE para que SAM ejecute pip
      BuildArchitecture: x86_64          # (o arm64, pero usa la misma que tu Lambda)

Outputs:
  CommonLayerArn:
    Description: "ARN of the common utils layer"
    Value: !Ref CommonLayer